# Generated by Django 2.2.11 on 2020-04-04 11:07

from django.db import migrations, models
import django.db.models.deletion
import restapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=4100)),
                ('attachments_json', models.CharField(max_length=4100)),
            ],
        ),
        migrations.CreateModel(
            name='IncomingMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_id', models.IntegerField()),
                ('text', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message_type', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=4100)),
                ('attachments_json', models.CharField(max_length=4100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('vk_id', models.IntegerField(unique=True)),
                ('state', models.CharField(max_length=255)),
                ('created_at', models.BigIntegerField(blank=True, default=restapi.models.get_time, help_text='format: Unix timestamp')),
                ('last_quiz_solve', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=4100)),
                ('text', models.CharField(max_length=4100)),
                ('answers_json', models.CharField(max_length=4100)),
                ('attachments', models.CharField(max_length=4100)),
                ('award_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restapi.Award')),
            ],
        ),
    ]
