# Generated by Django 2.2.11 on 2020-04-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20200404_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(default='begin', max_length=255),
        ),
    ]
