# Generated by Django 2.2.11 on 2020-04-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_user_solving_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='attachments',
            field=models.CharField(blank=True, max_length=4100, null=True),
        ),
    ]
