# Generated by Django 2.2.11 on 2020-04-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0008_auto_20200404_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='available',
            field=models.BigIntegerField(blank=True, default=None, help_text='format: Unix timestamp', null=True),
        ),
    ]
