# Generated by Django 2.2.11 on 2020-04-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0009_quiz_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='attachments_json',
            field=models.CharField(blank=True, default=None, max_length=4100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachments_json',
            field=models.CharField(blank=True, default=None, max_length=4100, null=True),
        ),
    ]
