# Generated by Django 2.2.11 on 2020-04-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0010_auto_20200405_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='attachments',
            new_name='attachments_json',
        ),
    ]
