# Generated by Django 2.2.11 on 2020-04-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0011_auto_20200405_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('secret_type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('text', models.CharField(blank=True, default=None, max_length=4100, null=True)),
                ('attachments_json', models.CharField(blank=True, default=None, max_length=4100, null=True)),
                ('available', models.BigIntegerField(blank=True, default=None, help_text='format: Unix timestamp', null=True)),
                ('order_type', models.IntegerField(default=0)),
            ],
        ),
    ]
