# Generated by Django 2.2.11 on 2020-04-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0012_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('command_type', models.CharField(max_length=255)),
                ('text', models.CharField(max_length=4100)),
                ('user_list', models.CharField(max_length=4100)),
                ('attachments_json', models.CharField(blank=True, default=None, max_length=4100, null=True)),
                ('available', models.BigIntegerField(blank=True, default=None, help_text='format: Unix timestamp', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(blank=True, max_length=4100, null=True),
        ),
    ]
