# Generated by Django 2.2.11 on 2020-04-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0013_auto_20200406_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='available',
        ),
        migrations.AddField(
            model_name='quiz',
            name='available_strtime',
            field=models.CharField(default='06.04.2020 12:00', max_length=255),
        ),
        migrations.AddField(
            model_name='quiz',
            name='available_unixtime',
            field=models.BigIntegerField(blank=True, default=0, help_text='format: Unix timestamp', null=True),
        ),
    ]
