# Generated by Django 2.2.11 on 2020-04-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0014_auto_20200406_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
