# Generated by Django 2.2.11 on 2020-04-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0015_auto_20200408_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='available_strtime',
            field=models.CharField(default='26.04.2020 12:00', max_length=255),
        ),
    ]
