# Generated by Django 2.2.11 on 2020-04-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0016_auto_20200408_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='extended_attachments_json',
            field=models.CharField(blank=True, default=None, max_length=4100, null=True),
        ),
        migrations.AddField(
            model_name='award',
            name='extended_text',
            field=models.CharField(blank=True, default=None, max_length=4100, null=True),
        ),
    ]
